service: lambtel-echo-bot

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}

functions:
  echo:
    handler: handler.echo
    events:
      - http:
          path: bot-webhook
          method: post
          cors: true
